#!/bin/sh

data="$HOME/.local/share/ttbl"
cache="$HOME/.cache/ttbl"
timetable="${cache}/timetable.json"

mkdir -p "$data"
mkdir -p "$cache"

# (string opt)
function recognise() {
	if [ ! -z "$1" ] && [ "$(echo "$1" | grep -e "+\?[0-9]\+" | wc -w)" -eq "0" ]; then
		echo "unrecognized option '$1'"
		get_help
		exit 0
	fi
}

# (string datePreference)
function print_date() {
	local datefmt="%Y%m%d"
	if [ -z "$1" ] || [ "$1" = "-0" ] || [ "$1" = "+0" ]; then # if no date preference
		if [ "$(date "+%H")" -gt "$2" ]; then #!! $2 is the time of end of day
			# if after school, present tmr classes
			fetch=$(date -v "+1d" "+%Y%m%d")
			printf "%s" "Here's"
		else

			fetch=$(date "+%Y%m%d")
			printf "%s" "It's"
		fi
	else
		date=$(echo "$1" | grep -e "[-+][0-9]\+")
		if [ -z "$date" ]; then
			date="$1"
			# the +2d is to handle weekends
			fetch=$(date -v "+2d" -v "${date}w" "+${datefmt}")
		else
			fetch=$(date -v "${date}d" "+${datefmt}")
		fi
		printf "%s" "Here's"
	fi
	date=$(date -j -f "$datefmt" "$fetch" "+%A")
	printf " %s. " "$date"
}

# => "period; room\t; subject; color"
function get_classes() {
	output=$(jq '.[]' < "$timetable" |
		jq -r '"\(.id); \(.periodName); \(.room)\t; \(.description); \(.startTime); \(.endTime); \(.teacherName); \(.colour)"')

	# date; remove empty lines; remove year number; remove W09; lowercase; remove ` - content`
	output=$(printf "%s" "$output" | sed -E "s/^[0-9]{6}-${fetch}; (.*)/\1/ ;
												s/^(.*;) (\t;.*)/\1 N\/A\2/ ;
												/^[0-9]{2}/d")
	printf "%s" "$output"
}

# (string classes)
function check_for_classes() {
	if [ "$(echo "$1" | wc -w)" -eq "0" ]; then # if no classes
		echo "There's no classes today, go do something productive."
		exit 0
	fi
}

# ==================== MAIN ===========================

recognise "$1"
print_date "$1" # print the Heres Wednesday"
output=$(get_classes) # get the classes from the current timetable
check_for_classes "$output" # check if theres any classes that day
printf "\n%s\n" "$output" | sed -E "s/\s*;\s*/;/g"
